# Generated by Django 4.2.5 on 2023-12-16 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storesong',
            options={'managed': True},
        ),
    ]
